chat_model:
  generator_kwargs:
      model: xtuner/llava-llama-3-8b-v1_1-transformers
      task: "image-to-text"
      generation_kwargs:
        max_new_tokens: 300
        do_sample: false
      huggingface_pipeline_kwargs:
        torch_dtype: torch.bfloat16
  generator_class: fastrag.generators.llava.LlavaHFGenerator
tools:
  - type: doc_with_image
    params:
      name: "docRetriever"
      description: 'useful for when you need to retrieve images and text to answer questions. Use the following format: {{ "input": [your tool input here ] }}.'
      pipeline_or_yaml_file: "config/empty_retrieval_pipeline.yaml"
system_tools:
  - type: doc_with_image_index_from_provider
    params:
      name: "docIndex"
      pipeline_or_yaml_file: "config/empty_index_pipeline.yaml"
      tool_provider_name: docRetriever